name = "sensibot"
main = "./src/index.ts"
node_compat = false

kv_namespaces = [{ binding = "KV", id = "e89d016a54a44aa1beb33433a264f741", preview_id = "e77e5de88ac641c98e2c8816a6096cc7" }]

compatibility_date = "2022-05-19"

[triggers]
crons = ["0 * * * *"]
# crons = ["*/10 * * * *"]

# [secrets]
# TOMORROW_API_KEY
# TOMORROW_LOCATION_ID
# SENSIBO_API_KEY
# SENSIBO_DEVICE_ID
# DISCORD_WEBHOOK_URL
# DISCORD_BOT_TOKEN
# DISCORD_CHANNEL_ID