name = "sensibot"
main = "./src/index.ts"

compatibility_date = "2022-05-11"

[triggers]
crons = ["0 * * * *"]
# crons = ["*/10 * * * *"]

# [secrets]
# TOMORROW_API_KEY
# TOMORROW_LOCATION_ID
# SENSIBO_API_KEY
# SENSIBO_DEVICE_ID
# DISCORD_WEBHOOK_URL
# DISCORD_BOT_TOKEN
# DISCORD_CHANNEL_ID